{
    'name': 'Packaging Table',
    'version': '1.0',
    'summary': 'Multi-record packaging table on product form with CBM/CFT auto calc',
    'category': 'Inventory',
    'author': 'Generated by ChatGPT for Anshika',
    'depends': ['product','stock'],
    'data': [
        'views/product_template_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
